server:
  port: 18087

spring:
  application:
    name: mall-aftersale
  config:
    import:
      - optional:nacos:mall-common.yaml?group=${NACOS_GROUP:MALL_GROUP}
      - optional:nacos:mall-aftersale.yaml?group=${NACOS_GROUP:MALL_GROUP}
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:MALL_GROUP}
        file-extension: yaml
      discovery:
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:MALL_GROUP}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
